version: '2'
services:
  tim---module:
    container_name: dylan-docker
    restart: always
    build: .
    tty: true
    ports: 
    - '80:3000'
    links:
    - postgres
  postgres: 
    container_name: postgres
    image: postgres
    ports:
    - '5432:5432'
