version: '3'
services:
  productionPG:
    image: postgres
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dylanmccarthy
      POSTGRES_PASSWORD: g
      POSTGRES_DB: shoedidas
    ports:
      - '5432:5432'